name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE_NAME: hoanganh26/demo-app
  HELM_REPO: app-helmchart
  HELM_CHART: app-demo
  HELM_VALUE_FILE: app-demo/app-demo-value.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          repository: MarcoLuw/demo-app
          ref: master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          VERSION: v1.${{ github.run_number }}
        run: |
          docker build . -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}
          docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}
          docker rmi ${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}

      - name: Checkout helm chart repo
        uses: actions/checkout@v3
        with:
          repository: MarcoLuw/app-helmchart
          ref: master
          path: ${{ env.HELM_REPO }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm values
        env:
          VERSION: v1.${{ github.run_number }}
        run: |
          cd ${{ env.HELM_REPO }}
          sed -i "s|  tag: .*|  tag: \"${{ env.VERSION }}\"|" ${{ env.HELM_VALUE_FILE }}
          sed -i "s|  repository: .* | repository: \"${{ env.DOCKER_IMAGE_NAME }}\"|" ${{ env.HELM_VALUE_FILE }}
          git config --global user.email "andrelu@lgcns.com"
          git config --global user.name "Andrelu"
          git add .
          git commit -m "Update to version ${{ env.VERSION }}"
          git push https://marcoluw:${{ secrets.GITHUB_TOKEN }}@github.com/marcoluw/app-helmchart.git